
server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: pixogram-auth
        uri: lb://pixogram-auth
        predicates:
        - Path= **/auth/**, **/user/**
        filters:
        - RewritePath=**/auth/(?<path>.*), /$\{path}
      - id: pixogram-friend
        uri: lb://pixogram-friend
        predicates:
        - Path=**/friends/**
        filters:
        - RewritePath=**/friends/(?<path>.*), /$\{path}
      - id: pixogram-images
        uri: lb://pixogram-images
        predicates:
        - Path=**/image**
        filters:
        - RewritePath=**/image**/(?<path>.*), /$\{path}
